### PR TITLE
Improved general look of some of the pages

### PR DESCRIPTION
**Pull request by jperrett256**

### CODE REVIEW

**Comment by jjd27** [comment]
On the 'Scales of Measure by Test Case' page, would it make sense to have the blue boxes wider so that the contents isn't so likely to wrap?

**Comment by jperrett256** [comment]
I've increased the length of the blue boxes on the 'Scales of Measure by Test Case' page (they also scale with the screen width, so will still wrap on smaller screens).
It used to just print the word "none" when there weren't any tests; made this into a blue box.

**Comment by jperrett256** [comment]
Just made the import jobs page a little bit prettier.

**Comment by jjd27** [comment]
Looks good, thanks!

**Pull request merged**
