### PR TITLE
Trivial CSS changes

### PR DESCRIPTION
**Pull request by jperrett256**
Only one noticeable change: made graph_title container look slightly better

### CODE REVIEW

**Comment by jjd27** [comment]
There's a strange bulge on the right-hand side of the box on the "import jobs" page in my browser. Is this intentional?

**Comment by jperrett256** [comment]
No.

**Comment by jjd27** [comment]
I also seem to have lost the box containing the "graph title" information. The contents spill over into wherever they can find bits of space. I prefer keeping that information together.

**Comment by jperrett256** [comment]
I have no idea why that's happening either. And the master branch works great in firefox, but everything seems broken in chrome now. Yesterday it worked fine.

**Comment by jperrett256** [comment]
Okay the master branch seems to be working fine. Chrome just caches things really well.

**Comment by jperrett256** [comment]
I've created pull #54 for you to test, it might fix the import page problem.

**Comment by jperrett256** [comment]
Is there anything that needs changing?

**Comment by jjd27** [comment]
Sorry, I also appear to have been a victim of browser caching. All looks good, thanks!

**Pull request merged**
